### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by ToeFungi** [urakozz/tesseract.ts#3]
Tried various methods and not sure why this is breaking in the manner it is...

Error
`var worker = new TesseractWorker(Object.assign({}, adapter.defaultOptions, wo`

Full stack trace

```
/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.js/dist/tesseract.js:535
        var worker = new TesseractWorker(Object.assign({}, adapter.defaultOptions, wo
                                                ^
TypeError: undefined is not a function
    at create (/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.js/dist/tesseract.js:535:42)
    at Object.../package.json (/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.js/dist/tesseract.js:626:18)
    at s (/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.js/dist/tesseract.js:1:685)
    at e (/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.js/dist/tesseract.js:1:856)
    at /Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.js/dist/tesseract.js:1:874
    at a (/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.js/dist/tesseract.js:1:150)
    at Object.<anonymous> (/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.js/dist/tesseract.js:1:387)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

source code

```TypeScript
import { Tesseract } from "tesseract.ts";

const rawImage = 'some-legit-base64-encoded-image'
const image = Buffer.from(rawImage, 'base64')

Tesseract.recognize(image)
  .progress(console.log)
  .then((res: any) => {
    console.log(res);
  })
  .catch(console.error);
```

package.json
```json
  "dependencies": {
    "@types/node": "^10.12.18",
    "tesseract.js": "^1.0.14",
    "tesseract.ts": "^1.0.3",
    "ts-node": "^7.0.1",
    "typescript": "^3.2.2"
  }
```

and I used
`tsc index.ts` followed by `node index.js` to run

**Comment by urakozz** [comment]
@ToeFungi I did it for the browser originally, didn't test it in node.js. Try version 1.1.0 
 https://github.com/urakozz/tesseract.ts/commit/b48d03e258c9ddeb022c3f07306b374b7585a29b

**Comment by ToeFungi** [comment]
@urakozz Thanks for the quick response. I tried the fix you submitted, got a new error

`var _instance = window ? require("tesseract.js/dist/tesseract") : require('tes...`
`ReferenceError: window is not defined`

Full trace
```
/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.ts/dist/index.js:3
var _instance = window ? require("tesseract.js/dist/tesseract") : require('tes
                ^
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/skaleb/Documents/personal/projects/test-ocr/node_modules/tesseract.ts/dist/index.js:3:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/skaleb/Documents/personal/projects/test-ocr/index.js:3:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by ToeFungi** [comment]
@urakozz Same problem, `window is not defined`

In `/dist/index.js:3` can you not add

```javascript
var window;
```

or will that overwrite/throw errors if the `window` object if present?

**Comment by urakozz** [comment]
if you use it in node.js, just write the following in your code and get rid of my lib :)

import * as TesseractTypes from "tesseract.js";
export const Tesseract: TesseractTypes.TesseractStatic = require('tesseract.js');

**Comment by ToeFungi** [comment]
@urakozz That does actually appear to work. Thanks for the help
